apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: mcr.microsoft.com/azure-sql-edge:1.0.4

          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "example_123"
          ports:
            - containerPort: 1433
          readinessProbe:
            tcpSocket:
              port: 1433
            initialDelaySeconds: 10
            periodSeconds: 5

          volumeMounts:
            - name: db-storage
              mountPath: /var/opt/mssql

      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
