apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-data-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/volume"
